
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtarqrjwgdxnpweyukdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0YXJxcmp3Z2R4bnB3ZXl1a2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Mjk5NDEsImV4cCI6MjA1OTIwNTk0MX0.6p3-SDm6zNwMSZHIgP41tCvaJUso3KVuIDZexopi9a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
